import os
import openai
from typing import List, Dict, Optional
import json
from datetime import datetime

class CityHistoryGenerator:
    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize the CityHistoryGenerator with OpenAI API key.
        
        Args:
            api_key: OpenAI API key. If None, will try to get from environment variable.
        """
        # Set up API key
        if api_key:
            self.api_key = api_key
        else:
            self.api_key = os.getenv('OPENAI_API_KEY')
            
        if not self.api_key:
            raise ValueError("OpenAI API key is required. Set OPENAI_API_KEY environment variable or pass api_key parameter.")
        
        # Configure OpenAI client
        openai.api_key = self.api_key
        
        # Default cities list
        self.cities = [
            'Paris', 'London', 'New York', 'Tokyo', 'Sydney', 
            'Berlin', 'Rome', 'Madrid', 'Moscow', 'Beijing'
        ]
    
    def generate_city_history(self, city: str) -> Dict[str, str]:
        """
        Generate a brief history for a single city using OpenAI API.
        
        Args:
            city: Name of the city
            
        Returns:
            Dictionary containing city name and generated history
        """
        try:
            prompt = f"""Write a brief, engaging history of {city} and its region. 
            Focus on key historical events, cultural significance, and notable developments. 
            Keep it concise (2-3 paragraphs) and informative for general readers."""
            
            response = openai.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are a knowledgeable historian specializing in urban history and cultural development."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=500,
                temperature=0.7
            )
            
            history = response.choices[0].message.content.strip() if response.choices[0].message.content else "No content generated"
            
            return {
                "city": city,
                "history": history,
                "generated_at": datetime.now().isoformat()
            }
            
        except openai.AuthenticationError:
            return {
                "city": city,
                "history": "Error: Invalid API key. Please check your OpenAI API credentials.",
                "error": "authentication_error"
            }
        except openai.RateLimitError:
            return {
                "city": city,
                "history": "Error: Rate limit exceeded. Please wait before making more requests.",
                "error": "rate_limit_error"
            }
        except openai.APIError as e:
            return {
                "city": city,
                "history": f"Error: OpenAI API error - {str(e)}",
                "error": "api_error"
            }
        except Exception as e:
            return {
                "city": city,
                "history": f"Error: Unexpected error - {str(e)}",
                "error": "general_error"
            }
    
    def generate_all_histories(self, cities: Optional[List[str]] = None) -> List[Dict[str, str]]:
        """
        Generate histories for all cities in the list.
        
        Args:
            cities: Optional list of cities. If None, uses default list.
            
        Returns:
            List of dictionaries containing city histories
        """
        if cities is None:
            cities = self.cities
        
        print(f"Generating histories for {len(cities)} cities...")
        print("=" * 50)
        
        histories = []
        for i, city in enumerate(cities, 1):
            print(f"Processing {i}/{len(cities)}: {city}")
            history_data = self.generate_city_history(city)
            histories.append(history_data)
            
            # Add a small delay to avoid rate limiting
            import time
            time.sleep(0.5)
        
        return histories
    
    def print_histories(self, histories: List[Dict[str, str]]) -> None:
        """
        Print all histories in a readable format.
        
        Args:
            histories: List of history dictionaries
        """
        print("\n" + "=" * 60)
        print("CITY HISTORIES GENERATED BY OPENAI")
        print("=" * 60)
        
        for history_data in histories:
            city = history_data["city"]
            history = history_data["history"]
            generated_at = history_data.get("generated_at", "Unknown")
            
            print(f"\n🏙️  {city.upper()}")
            print("-" * (len(city) + 4))
            print(history)
            print(f"\nGenerated: {generated_at}")
            print("=" * 60)
    
    def save_histories_to_file(self, histories: List[Dict[str, str]], filename: str = "city_histories.json") -> None:
        """
        Save histories to a JSON file.
        
        Args:
            histories: List of history dictionaries
            filename: Name of the output file
        """
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                json.dump(histories, f, indent=2, ensure_ascii=False)
            print(f"\n✅ Histories saved to {filename}")
        except Exception as e:
            print(f"❌ Error saving to file: {e}")


def main():
    """
    Main function to demonstrate the CityHistoryGenerator.
    """
    print("🌍 City History Generator using OpenAI API")
    print("=" * 50)
    
    # Check for API key
    api_key = os.getenv('OPENAI_API_KEY')
    if not api_key:
        print("⚠️  Warning: OPENAI_API_KEY environment variable not set.")
        print("Please set your OpenAI API key:")
        print("export OPENAI_API_KEY='your-api-key-here'")
        print("\nOr you can enter it manually when prompted.")
        
        # Option to enter API key manually
        manual_key = input("\nEnter your OpenAI API key (or press Enter to exit): ").strip()
        if not manual_key:
            print("Exiting...")
            return
        api_key = manual_key
    
    try:
        # Initialize the generator
        generator = CityHistoryGenerator(api_key)
        
        # Generate histories for all cities
        histories = generator.generate_all_histories()
        
        # Print the results
        generator.print_histories(histories)
        
        # Save to file
        generator.save_histories_to_file(histories)
        
        print("\n🎉 City history generation completed!")
        
    except ValueError as e:
        print(f"❌ Error: {e}")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")


if __name__ == "__main__":
    main() 